//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Comment
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public Nullable<int> PhotoId { get; set; }
    public Nullable<int> TextId { get; set; }
    public string Detail { get; set; }
    public bool isActive { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public string Name { get; set; }
    public string SurName { get; set; }
}

public partial class Followed
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int FollowedUserId { get; set; }
    public bool isActive { get; set; }
}

public partial class Follower
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int FollowerUserId { get; set; }
    public bool isActive { get; set; }
    public Nullable<bool> isApproval { get; set; }
}

public partial class Like
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public Nullable<int> PhotoId { get; set; }
    public Nullable<int> TextId { get; set; }
    public bool isActive { get; set; }
    public string Name { get; set; }
    public string SurName { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<bool> isLike { get; set; }
}

public partial class Photo
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public string PhotoPath { get; set; }
    public string AltText { get; set; }
    public bool isActive { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<int> TrendPostCount { get; set; }
}

public partial class SenderMessageDetail
{
    public int Id { get; set; }
    public string MessageDetail { get; set; }
    public int SenderId { get; set; }
    public int ReceiverId { get; set; }
    public System.DateTime Time { get; set; }
    public bool isActive { get; set; }
    public Nullable<int> UserMessageId { get; set; }
}

public partial class Text
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public string Title { get; set; }
    public string Detail { get; set; }
    public bool isActive { get; set; }
}

public partial class User
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string City { get; set; }
    public Nullable<System.DateTime> BirthDate { get; set; }
    public string Email { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Photo { get; set; }
    public bool isHide { get; set; }
    public bool isActive { get; set; }
    public string AboutMe { get; set; }
    public string Education { get; set; }
    public string Location { get; set; }
}

public partial class UserMessage
{
    public int Id { get; set; }
    public int SenderId { get; set; }
    public int ReceiverId { get; set; }
    public bool isActive { get; set; }
    public Nullable<System.DateTime> Time { get; set; }
}
